/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Cliente
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnInicial = new javax.swing.JPanel();
        lbCorpo = new javax.swing.JLabel();
        lbBracoEsquerdo = new javax.swing.JLabel();
        lbCabeca = new javax.swing.JLabel();
        lbBracoDireito = new javax.swing.JLabel();
        lbPernaEsquerda = new javax.swing.JLabel();
        lbPernaDireita = new javax.swing.JLabel();
        lbForca = new javax.swing.JLabel();
        lbtxtDa = new javax.swing.JLabel();
        lbtxtForca = new javax.swing.JLabel();
        lbtxtJogo = new javax.swing.JLabel();
        btJogar = new javax.swing.JButton();
        lbBackgroundInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnInicial.setLayout(null);

        lbCorpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/corpoStick.png"))); // NOI18N
        pnInicial.add(lbCorpo);
        lbCorpo.setBounds(160, 320, 100, 100);

        lbBracoEsquerdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/braçoEsquerdo.png"))); // NOI18N
        pnInicial.add(lbBracoEsquerdo);
        lbBracoEsquerdo.setBounds(150, 370, 30, 30);

        lbCabeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabeçaStick.png"))); // NOI18N
        pnInicial.add(lbCabeca);
        lbCabeca.setBounds(160, 260, 100, 100);

        lbBracoDireito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/braçoDireito.png"))); // NOI18N
        pnInicial.add(lbBracoDireito);
        lbBracoDireito.setBounds(240, 370, 30, 30);

        lbPernaEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pernaEsqueda.png"))); // NOI18N
        pnInicial.add(lbPernaEsquerda);
        lbPernaEsquerda.setBounds(170, 400, 40, 40);

        lbPernaDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pernaDireita.png"))); // NOI18N
        pnInicial.add(lbPernaDireita);
        lbPernaDireita.setBounds(210, 400, 40, 40);

        lbForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forca.png"))); // NOI18N
        pnInicial.add(lbForca);
        lbForca.setBounds(0, 140, 250, 305);

        lbtxtDa.setBackground(new java.awt.Color(255, 255, 255));
        lbtxtDa.setFont(new java.awt.Font("HP Simplified", 0, 70)); // NOI18N
        lbtxtDa.setForeground(new java.awt.Color(255, 0, 0));
        lbtxtDa.setText("Da");
        pnInicial.add(lbtxtDa);
        lbtxtDa.setBounds(410, 90, 90, 100);

        lbtxtForca.setFont(new java.awt.Font("HP Simplified", 0, 70)); // NOI18N
        lbtxtForca.setForeground(new java.awt.Color(0, 255, 255));
        lbtxtForca.setText("Forca");
        pnInicial.add(lbtxtForca);
        lbtxtForca.setBounds(370, 160, 170, 90);

        lbtxtJogo.setBackground(new java.awt.Color(255, 255, 255));
        lbtxtJogo.setFont(new java.awt.Font("HP Simplified", 0, 70)); // NOI18N
        lbtxtJogo.setForeground(new java.awt.Color(255, 255, 51));
        lbtxtJogo.setText("Jogo");
        pnInicial.add(lbtxtJogo);
        lbtxtJogo.setBounds(380, 30, 140, 70);

        btJogar.setBackground(new java.awt.Color(255, 255, 153));
        btJogar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btJogar.setForeground(new java.awt.Color(0, 102, 153));
        btJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jogar.png"))); // NOI18N
        btJogar.setText("Jogar");
        pnInicial.add(btJogar);
        btJogar.setBounds(350, 310, 200, 70);

        lbBackgroundInicial.setFont(new java.awt.Font("HP Simplified", 0, 70)); // NOI18N
        lbBackgroundInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        lbBackgroundInicial.setToolTipText("");
        pnInicial.add(lbBackgroundInicial);
        lbBackgroundInicial.setBounds(0, 0, 710, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JLabel lbBackgroundInicial;
    private javax.swing.JLabel lbBracoDireito;
    private javax.swing.JLabel lbBracoEsquerdo;
    private javax.swing.JLabel lbCabeca;
    private javax.swing.JLabel lbCorpo;
    private javax.swing.JLabel lbForca;
    private javax.swing.JLabel lbPernaDireita;
    private javax.swing.JLabel lbPernaEsquerda;
    private javax.swing.JLabel lbtxtDa;
    private javax.swing.JLabel lbtxtForca;
    private javax.swing.JLabel lbtxtJogo;
    private javax.swing.JPanel pnInicial;
    // End of variables declaration//GEN-END:variables
}
