/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.CalculadoraFinanceira;
/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {
    
    CalculadoraFinanceira cf = new CalculadoraFinanceira();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jptitulo = new javax.swing.JPanel();
        lbtitulo = new javax.swing.JLabel();
        lbvista = new javax.swing.JLabel();
        tfvista = new javax.swing.JTextField();
        lbparcela = new javax.swing.JLabel();
        tfparcela = new javax.swing.JTextField();
        lbjuros = new javax.swing.JLabel();
        tfjuros = new javax.swing.JTextField();
        lbqtde = new javax.swing.JLabel();
        tfqtde = new javax.swing.JTextField();
        jpprazo = new javax.swing.JPanel();
        lbprazo = new javax.swing.JLabel();
        tfprazo = new javax.swing.JTextField();
        btvista = new javax.swing.JButton();
        btparcela = new javax.swing.JButton();
        btjuros = new javax.swing.JButton();
        btqtde = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jptitulo.setBackground(new java.awt.Color(9, 190, 46));

        lbtitulo.setFont(new java.awt.Font("OCR A Std", 0, 18)); // NOI18N
        lbtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitulo.setText("Calculadora Financeira");

        javax.swing.GroupLayout jptituloLayout = new javax.swing.GroupLayout(jptitulo);
        jptitulo.setLayout(jptituloLayout);
        jptituloLayout.setHorizontalGroup(
            jptituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtitulo)
                .addGap(50, 50, 50))
        );
        jptituloLayout.setVerticalGroup(
            jptituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptituloLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbvista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbvista.setText("Valor a Vista:");

        tfvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvistaActionPerformed(evt);
            }
        });

        lbparcela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbparcela.setText("Valor da Parcela:");

        lbjuros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbjuros.setText("Taxa de Juros:");

        lbqtde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbqtde.setText("Qtde Parcelas:");

        jpprazo.setBorder(new javax.swing.border.MatteBorder(null));

        lbprazo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbprazo.setText("Total a Prazo:");

        javax.swing.GroupLayout jpprazoLayout = new javax.swing.GroupLayout(jpprazo);
        jpprazo.setLayout(jpprazoLayout);
        jpprazoLayout.setHorizontalGroup(
            jpprazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpprazoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbprazo)
                .addGap(18, 18, 18)
                .addComponent(tfprazo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jpprazoLayout.setVerticalGroup(
            jpprazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpprazoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpprazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbprazo)
                    .addComponent(tfprazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btvista.setText("Calcular");
        btvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvistaActionPerformed(evt);
            }
        });

        btparcela.setText("Calcular");
        btparcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btparcelaActionPerformed(evt);
            }
        });

        btjuros.setText("Calcular");
        btjuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjurosActionPerformed(evt);
            }
        });

        btqtde.setText("Calcular");
        btqtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btqtdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jptitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbvista)
                    .addComponent(lbparcela)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbqtde)
                        .addComponent(lbjuros)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfvista)
                    .addComponent(tfparcela)
                    .addComponent(tfjuros)
                    .addComponent(tfqtde, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btvista)
                    .addComponent(btparcela)
                    .addComponent(btjuros)
                    .addComponent(btqtde))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jpprazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jptitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbvista)
                    .addComponent(tfvista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btvista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbparcela)
                    .addComponent(tfparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btparcela))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbjuros)
                    .addComponent(tfjuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btjuros))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbqtde)
                    .addComponent(tfqtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btqtde))
                .addGap(19, 19, 19)
                .addComponent(jpprazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvistaActionPerformed

    private void btvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvistaActionPerformed
        // TODO add your handling code here:
        double vp = Double.parseDouble(tfparcela.getText());
        double taxa = Double.parseDouble(tfjuros.getText());
        taxa = taxa / 100;
        int qtde = Integer.parseInt(tfqtde.getText());
        double valor = cf.vista(vp, taxa, qtde);
        tfvista.setText(String.valueOf(valor));
    }//GEN-LAST:event_btvistaActionPerformed

    private void btparcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btparcelaActionPerformed
        // TODO add your handling code here:
        double vv = Double.parseDouble(tfvista.getText());
        double taxa = Double.parseDouble(tfjuros.getText());
        taxa = taxa / 100;
        int qtde = Integer.parseInt(tfqtde.getText());
        double valor = cf.parcela(vv, taxa, qtde);
        tfparcela.setText(String.valueOf(valor));
    
    }//GEN-LAST:event_btparcelaActionPerformed

    private void btjurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjurosActionPerformed
        // TODO add your handling code here:
        double vv = Double.parseDouble(tfvista.getText());
        double vp = Double.parseDouble(tfparcela.getText());
        int qtde = Integer.parseInt(tfqtde.getText());
        double taxa = cf.taxa(vv, vp, qtde);
        taxa = taxa * 100;
        tfjuros.setText(String.valueOf(taxa));
    }//GEN-LAST:event_btjurosActionPerformed

    private void btqtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btqtdeActionPerformed
        // TODO add your handling code here:
        double vv = Double.parseDouble(tfvista.getText());
        double vp = Double.parseDouble(tfparcela.getText());
        double taxa = Double.parseDouble(tfjuros.getText());
        taxa = taxa / 100;
        int qtde = cf.periodo(vv, vp, taxa);
        tfqtde.setText(String.valueOf(qtde));
    }//GEN-LAST:event_btqtdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btjuros;
    private javax.swing.JButton btparcela;
    private javax.swing.JButton btqtde;
    private javax.swing.JButton btvista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpprazo;
    private javax.swing.JPanel jptitulo;
    private javax.swing.JLabel lbjuros;
    private javax.swing.JLabel lbparcela;
    private javax.swing.JLabel lbprazo;
    private javax.swing.JLabel lbqtde;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JLabel lbvista;
    private javax.swing.JTextField tfjuros;
    private javax.swing.JTextField tfparcela;
    private javax.swing.JTextField tfprazo;
    private javax.swing.JTextField tfqtde;
    private javax.swing.JTextField tfvista;
    // End of variables declaration//GEN-END:variables
}
