/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author adm-dev
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panJogo = new javax.swing.JPanel();
        panStick = new javax.swing.JPanel();
        lblCabecaStick = new javax.swing.JLabel();
        lblCorpoStick = new javax.swing.JLabel();
        lblMaoDirStick = new javax.swing.JLabel();
        lblMaoEsqStick = new javax.swing.JLabel();
        lblPernaDirStick = new javax.swing.JLabel();
        lblPernaEsqStick = new javax.swing.JLabel();
        panErros = new javax.swing.JPanel();
        lblErros = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnDica = new javax.swing.JButton();
        btnTentar = new javax.swing.JButton();
        lblDicas = new javax.swing.JLabel();
        lblTotalDicas = new javax.swing.JLabel();
        lblPalavra = new javax.swing.JLabel();
        txtTentativa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panStick.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblCabecaStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabeçaStick.png"))); // NOI18N

        lblCorpoStick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorpoStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/corpoStick.png"))); // NOI18N
        lblCorpoStick.setToolTipText("");

        lblMaoDirStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/direitaStick.png"))); // NOI18N

        lblMaoEsqStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerdaStick.png"))); // NOI18N

        lblPernaDirStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/direitaStick.png"))); // NOI18N

        lblPernaEsqStick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerdaStick.png"))); // NOI18N

        javax.swing.GroupLayout panStickLayout = new javax.swing.GroupLayout(panStick);
        panStick.setLayout(panStickLayout);
        panStickLayout.setHorizontalGroup(
            panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panStickLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCabecaStick)
                    .addGroup(panStickLayout.createSequentialGroup()
                        .addGroup(panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaoEsqStick)
                            .addComponent(lblPernaEsqStick))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorpoStick, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaoDirStick)
                    .addComponent(lblPernaDirStick))
                .addGap(67, 67, 67))
        );
        panStickLayout.setVerticalGroup(
            panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCabecaStick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panStickLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panStickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panStickLayout.createSequentialGroup()
                                .addComponent(lblMaoDirStick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPernaDirStick))
                            .addComponent(lblCorpoStick, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaoEsqStick)))
                    .addGroup(panStickLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblPernaEsqStick)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panErros.setBorder(javax.swing.BorderFactory.createTitledBorder("Erros"));

        lblErros.setText("<vazio>");

        javax.swing.GroupLayout panErrosLayout = new javax.swing.GroupLayout(panErros);
        panErros.setLayout(panErrosLayout);
        panErrosLayout.setHorizontalGroup(
            panErrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panErrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErros)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panErrosLayout.setVerticalGroup(
            panErrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panErrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErros)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnDica.setText("Dica");
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });

        btnTentar.setText("Tentar!");
        btnTentar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTentarMouseClicked(evt);
            }
        });
        btnTentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarActionPerformed(evt);
            }
        });

        lblDicas.setText("0");

        lblTotalDicas.setText("/ 3");

        lblPalavra.setText("<vazio>");
        lblPalavra.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblPalavraInputMethodTextChanged(evt);
            }
        });

        txtTentativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTentativaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panJogoLayout = new javax.swing.GroupLayout(panJogo);
        panJogo.setLayout(panJogoLayout);
        panJogoLayout.setHorizontalGroup(
            panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogoLayout.createSequentialGroup()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addComponent(panStick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addComponent(panErros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addComponent(lblDicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalDicas)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addComponent(btnDica, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPalavra))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJogoLayout.createSequentialGroup()
                        .addComponent(btnTentar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        panJogoLayout.setVerticalGroup(
            panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJogoLayout.createSequentialGroup()
                .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panJogoLayout.createSequentialGroup()
                        .addGroup(panJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(lblDicas)
                            .addComponent(lblTotalDicas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDica))
                    .addGroup(panJogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panErros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panStick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPalavra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txtTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTentar)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtTentativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTentativaActionPerformed
        txtTentativa.getText();
    }//GEN-LAST:event_txtTentativaActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDicaActionPerformed

    private void btnTentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTentarActionPerformed

    private void btnTentarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentarMouseClicked
        String Tentativa = txtTentativa.getText();
        limpaTela();
    }//GEN-LAST:event_btnTentarMouseClicked

    private void lblPalavraInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblPalavraInputMethodTextChanged
       
    }//GEN-LAST:event_lblPalavraInputMethodTextChanged

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        TelaMenu tela = new TelaMenu();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked
        
        private void limpaTela() {
        txtTentativa.setText("");
        txtTentativa.requestFocus();
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDica;
    private javax.swing.JButton btnTentar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCabecaStick;
    private javax.swing.JLabel lblCorpoStick;
    private javax.swing.JLabel lblDicas;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblMaoDirStick;
    private javax.swing.JLabel lblMaoEsqStick;
    private javax.swing.JLabel lblPalavra;
    private javax.swing.JLabel lblPernaDirStick;
    private javax.swing.JLabel lblPernaEsqStick;
    private javax.swing.JLabel lblTotalDicas;
    private javax.swing.JPanel panErros;
    private javax.swing.JPanel panJogo;
    private javax.swing.JPanel panStick;
    private javax.swing.JTextField txtTentativa;
    // End of variables declaration//GEN-END:variables
}
