/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    
    
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int resp = JOptionPane.showConfirmDialog(null,
                            "Tem certeza que deseja sair?",
                            "Confirmação",
                            JOptionPane.OK_CANCEL_OPTION);
                if (resp == JOptionPane.OK_OPTION) System.exit(0);
            }
        });
    }
            



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        pnCors = new javax.swing.JPanel();
        lbCors = new javax.swing.JLabel();
        pnVermelho = new javax.swing.JPanel();
        lbVermelho = new javax.swing.JLabel();
        pnAmarelo = new javax.swing.JPanel();
        lbAmarelo = new javax.swing.JLabel();
        pnVerde = new javax.swing.JPanel();
        lbVerde = new javax.swing.JLabel();
        pnAzul = new javax.swing.JPanel();
        lbAzul = new javax.swing.JLabel();
        pnRoxo = new javax.swing.JPanel();
        lbRoxo = new javax.swing.JLabel();
        pnCampos = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnTitulo.setBackground(new java.awt.Color(150, 238, 168));
        pnTitulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));

        lbTitulo.setBackground(new java.awt.Color(0, 51, 255));
        lbTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(51, 102, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Colorindo com o Mouse");
        lbTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(93, 93, 93))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbTitulo)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnCors.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        lbCors.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        lbCors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCors.setText("COR SELECIONADA");
        lbCors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnCorsLayout = new javax.swing.GroupLayout(pnCors);
        pnCors.setLayout(pnCorsLayout);
        pnCorsLayout.setHorizontalGroup(
            pnCorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCorsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCors)
                .addGap(134, 134, 134))
        );
        pnCorsLayout.setVerticalGroup(
            pnCorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCors)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnVermelho.setBackground(new java.awt.Color(204, 0, 0));
        pnVermelho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnVermelho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnVermelhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnVermelhoMouseExited(evt);
            }
        });

        lbVermelho.setForeground(new java.awt.Color(240, 240, 240));
        lbVermelho.setText("VERMELHO");

        javax.swing.GroupLayout pnVermelhoLayout = new javax.swing.GroupLayout(pnVermelho);
        pnVermelho.setLayout(pnVermelhoLayout);
        pnVermelhoLayout.setHorizontalGroup(
            pnVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVermelhoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lbVermelho)
                .addGap(31, 31, 31))
        );
        pnVermelhoLayout.setVerticalGroup(
            pnVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVermelhoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbVermelho)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnAmarelo.setBackground(new java.awt.Color(255, 255, 0));
        pnAmarelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnAmarelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnAmareloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnAmareloMouseExited(evt);
            }
        });

        lbAmarelo.setForeground(new java.awt.Color(51, 51, 51));
        lbAmarelo.setText("AMARELO");

        javax.swing.GroupLayout pnAmareloLayout = new javax.swing.GroupLayout(pnAmarelo);
        pnAmarelo.setLayout(pnAmareloLayout);
        pnAmareloLayout.setHorizontalGroup(
            pnAmareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAmareloLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lbAmarelo)
                .addGap(31, 31, 31))
        );
        pnAmareloLayout.setVerticalGroup(
            pnAmareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAmareloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbAmarelo)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnVerde.setBackground(new java.awt.Color(51, 255, 0));
        pnVerde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnVerdeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnVerdeMouseExited(evt);
            }
        });

        lbVerde.setText("VERDE");

        javax.swing.GroupLayout pnVerdeLayout = new javax.swing.GroupLayout(pnVerde);
        pnVerde.setLayout(pnVerdeLayout);
        pnVerdeLayout.setHorizontalGroup(
            pnVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVerdeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbVerde)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnVerdeLayout.setVerticalGroup(
            pnVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVerdeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbVerde)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnAzul.setBackground(new java.awt.Color(0, 0, 255));
        pnAzul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnAzulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnAzulMouseExited(evt);
            }
        });

        lbAzul.setForeground(new java.awt.Color(240, 240, 240));
        lbAzul.setText("AZUL");

        javax.swing.GroupLayout pnAzulLayout = new javax.swing.GroupLayout(pnAzul);
        pnAzul.setLayout(pnAzulLayout);
        pnAzulLayout.setHorizontalGroup(
            pnAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAzulLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbAzul)
                .addGap(38, 38, 38))
        );
        pnAzulLayout.setVerticalGroup(
            pnAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAzulLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbAzul)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnRoxo.setBackground(new java.awt.Color(204, 0, 204));
        pnRoxo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnRoxo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnRoxoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnRoxoMouseExited(evt);
            }
        });

        lbRoxo.setText("ROXO");

        javax.swing.GroupLayout pnRoxoLayout = new javax.swing.GroupLayout(pnRoxo);
        pnRoxo.setLayout(pnRoxoLayout);
        pnRoxoLayout.setHorizontalGroup(
            pnRoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRoxoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbRoxo)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnRoxoLayout.setVerticalGroup(
            pnRoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRoxoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbRoxo)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnCampos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNome.setText("Nome:");

        lbEmail.setText("Email:");

        tfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeFocusLost(evt);
            }
        });

        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCamposLayout = new javax.swing.GroupLayout(pnCampos);
        pnCampos.setLayout(pnCamposLayout);
        pnCamposLayout.setHorizontalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(lbEmail))
                .addGap(18, 18, 18)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNome)
                    .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCamposLayout.setVerticalGroup(
            pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnCors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnRoxo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRoxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnVermelhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVermelhoMouseEntered
       lbCors.setForeground(pnVermelho.getBackground());
    }//GEN-LAST:event_pnVermelhoMouseEntered

    private void pnVermelhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVermelhoMouseExited
       setBlack();
    }//GEN-LAST:event_pnVermelhoMouseExited

    private void pnAmareloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAmareloMouseEntered
       lbCors.setForeground(pnAmarelo.getBackground());
    }//GEN-LAST:event_pnAmareloMouseEntered

    private void pnAmareloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAmareloMouseExited
       setBlack();
    }//GEN-LAST:event_pnAmareloMouseExited

    private void pnVerdeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVerdeMouseEntered
       lbCors.setForeground(pnVerde.getBackground());
    }//GEN-LAST:event_pnVerdeMouseEntered

    private void pnVerdeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVerdeMouseExited
       setBlack();
    }//GEN-LAST:event_pnVerdeMouseExited

    private void pnAzulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAzulMouseEntered
       lbCors.setForeground(pnAzul.getBackground());
    }//GEN-LAST:event_pnAzulMouseEntered

    private void pnAzulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAzulMouseExited
       setBlack();
    }//GEN-LAST:event_pnAzulMouseExited

    private void pnRoxoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRoxoMouseEntered
       lbCors.setForeground(pnRoxo.getBackground());
    }//GEN-LAST:event_pnRoxoMouseEntered

    private void pnRoxoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRoxoMouseExited
       setBlack();
    }//GEN-LAST:event_pnRoxoMouseExited

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusGained
       tfNome.setBackground(Color.yellow);
    }//GEN-LAST:event_tfNomeFocusGained

    private void tfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusLost
       tfNome.setBackground(Color.white);
    }//GEN-LAST:event_tfNomeFocusLost

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
       tfEmail.setBackground(Color.yellow);
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
       tfEmail.setBackground(Color.white);
    }//GEN-LAST:event_tfEmailFocusLost
        
        private void setBlack(){
           lbCors.setForeground(Color.black);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAmarelo;
    private javax.swing.JLabel lbAzul;
    private javax.swing.JLabel lbCors;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRoxo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVerde;
    private javax.swing.JLabel lbVermelho;
    private javax.swing.JPanel pnAmarelo;
    private javax.swing.JPanel pnAzul;
    private javax.swing.JPanel pnCampos;
    private javax.swing.JPanel pnCors;
    private javax.swing.JPanel pnRoxo;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JPanel pnVerde;
    private javax.swing.JPanel pnVermelho;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
